var name1 = "Ahmed";
var name2 = "Ahmed";
var name3 = "Ahmed";
/** following code show error */
// var name4=10;
// name4:number=25;
console.log(name1);
console.log(name2);
console.log(name3);
var aN = 10;
var bN = 20;
var cN = 30;
console.log(aN);
console.log(bN);
console.log(cN);
var active = true;
var inactive = false;
console.log(active);
console.log(inactive);
var mark1 = [1, 2, 3, 4, 5];
console.log(mark1[0]);
console.log(mark1[1]);
console.log(mark1[2]);
console.log(mark1[3]);
console.log(mark1[4]);
console.log(mark1[5]);
var class1 = ["Ahmed", "Ali"];
var class2 = ["Ahmed", "Ali", "Mohamed"];
var class3 = ["Ahmed", "Ali", "Mohamed", "Sayed"];
console.log(class1);
